### ISSUE TITLE
Include node_modules in .gitignore

### ISSUE THREAD

**Issue by ghost** [CurosMJ/gdg-trailblazer#1]
node_modules should be ignored. Since dependencies will have to be installed (or updated in this repository). It will increase the repository size and no. of additions / deletions in commits only.

**Comment by CurosMJ** [comment]
committing `node_modules` ensures that THE correct version is used for the dependency, and no anomaly is seen while development and in production. Maybe you're right, will look into this. 

P.S. Sorry for late reply, I didn't notice this. Thanks :)

**Comment by CurosMJ** [comment]
@dhruvin2910 http://stackoverflow.com/questions/11459475/should-i-check-in-node-modules-to-git-when-creating-a-node-js-app-on-heroku 

This is the article I had considered.

**Comment by dhruvin2910** [comment]
Writing vaguely, git should be used as a VCS for source code. The problem being solved by not adding external libraries doesn't exist anymore (not that I know).

I've been using heroku and never faced this npm problem. And as of now, when node is shipped with LTS and npm is very stable, I think you may gitignore that.

Yeah and the issue (potential) I raised will only occur if you ```npm update``` locally (since the versions of dependencies are **NOT** mentioned exactly ```(used ^M.m.b)```).

One possible workaround might be hard-coding current (stable) versions of dependencies in ```package.json```. Because that will prevent deps from updating (specially when an outside collaborator wants to contribute, and he/she doesn't know not to npm update).

**Comment by dhruvin2910** [comment]
I would handle it for you, if you so.

**Comment by CurosMJ** [comment]
Did you read the answer?

> Usually, no. Allow npm to resolve dependencies for your packages.
>
> For packages you deploy, such as websites and apps, you should use npm shrinkwrap to lock down 
> your full dependency tree:

> https://docs.npmjs.com/cli/shrinkwrap

**Comment by dhruvin2910** [comment]
Yes I read the answer, and they are no longer recommending node_modules folder be committed.
I could not understand the point you were drawing by last comment. So can you just tell me if you are in favor of gitignoring deps or not.

**Comment by CurosMJ** [comment]
I am in favor of gitignoring deps, but, since this ain't a library, this is a deployable app, we should go with shrinkwrapping, that it is the only way to lock down dependencies here.

**Comment by CurosMJ** [comment]
I believe, shrikwrapping was not available at the time they suggested committing whole node_modules directory, since that was the only way to lock dependencies. Since we have shrinkwrap now, we should use it to lock down dependencies.

**Comment by dhruvin2910** [comment]
I agree, and I think we should go with shrinkwrapping.
